FROM amazoncorretto:11-alpine-jdk //de que imagen se parte
MAINTAINER ANNIE //quien es el dueño
COPY target/mgb-0.0.1-SNAPSHOT.jar mgb-app.jar  //va a copiar el empaquetado a  github 
ENTRYPOINT ["java","-jar","/mgb-app.jar.jar"]   //instruccion que se va a ejecutar primero